# Generated by Django 5.1.7 on 2025-04-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_executado_planejado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executado',
            name='content',
        ),
        migrations.RemoveField(
            model_name='planejado',
            name='content',
        ),
        migrations.AddField(
            model_name='executado',
            name='auc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='executado',
            name='contratacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executado',
            name='entrevistas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executado',
            name='headcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executado',
            name='nps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executado',
            name='receita',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='planejado',
            name='auc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='planejado',
            name='contratacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planejado',
            name='entrevistas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planejado',
            name='headcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planejado',
            name='nps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planejado',
            name='receita',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
