# Generated by Django 5.1.7 on 2025-04-18 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_executado_content_remove_planejado_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('auc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='AUC R$ (on+offshore)')),
                ('receita', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Receita R$ (PJ1+PJ2)')),
                ('headcount', models.IntegerField(verbose_name='Headcount')),
                ('entrevistas', models.IntegerField(verbose_name='Entrevistas')),
                ('contratacoes', models.IntegerField(verbose_name='Contratações')),
                ('nps', models.IntegerField(verbose_name='NPS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
