# Generated by Django 5.1.7 on 2025-04-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_captacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captacao',
            name='auc',
        ),
        migrations.RemoveField(
            model_name='captacao',
            name='contratacoes',
        ),
        migrations.RemoveField(
            model_name='captacao',
            name='entrevistas',
        ),
        migrations.RemoveField(
            model_name='captacao',
            name='headcount',
        ),
        migrations.RemoveField(
            model_name='captacao',
            name='nps',
        ),
        migrations.RemoveField(
            model_name='captacao',
            name='receita',
        ),
        migrations.AddField(
            model_name='captacao',
            name='acao',
            field=models.CharField(choices=[('Marcar 1ª Reunião', 'Marcar 1ª Reunião'), ('Marcar 2ª Reunião', 'Marcar 2ª Reunião'), ('Abrir conta', 'Abrir conta'), ('Pedir TED', 'Pedir TED'), ('Trocar Assessoria', 'Trocar Assessoria'), ('Fazer STVM', 'Fazer STVM')], default='Marcar 1ª Reunião', max_length=50, verbose_name='Ação'),
        ),
        migrations.AddField(
            model_name='captacao',
            name='nome',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='captacao',
            name='origem',
            field=models.CharField(choices=[('Família', 'Família'), ('Relacionamento', 'Relacionamento'), ('Indicação', 'Indicação'), ('Redes Sociais', 'Redes Sociais'), ('Palestras', 'Palestras'), ('Alunos', 'Alunos'), ('Já é cliente', 'Já é cliente')], default='Família', max_length=50, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='captacao',
            name='pl',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Pl'),
        ),
        migrations.AddField(
            model_name='captacao',
            name='planejado_migracao',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Planejado Migração'),
        ),
        migrations.AddField(
            model_name='captacao',
            name='status',
            field=models.CharField(choices=[('Quente', 'Quente'), ('Morno', 'Morno'), ('Frio', 'Frio')], default='Quente', max_length=50, verbose_name='Status'),
        ),
    ]
