# Generated by Django 5.1.7 on 2025-04-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_captacao_auc_remove_captacao_contratacoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('dia_inicio', models.IntegerField()),
                ('dia_fim', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='captacao',
            name='nome',
            field=models.CharField(default='...', max_length=255, verbose_name='Nome do cliente'),
        ),
        migrations.AlterField(
            model_name='captacao',
            name='pl',
            field=models.CharField(default='R$ 0,00', max_length=255, verbose_name='PL (Total em milhões)'),
        ),
        migrations.AlterField(
            model_name='captacao',
            name='planejado_migracao',
            field=models.CharField(default='R$ 0,00', max_length=255, verbose_name='Planejado Migração'),
        ),
        migrations.CreateModel(
            name='AgendamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Planejado', 'Planejado'), ('Executado', 'Executado')], max_length=20)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('dia_inicio', models.IntegerField()),
                ('dia_fim', models.IntegerField()),
            ],
            options={
                'unique_together': {('nome', 'mes', 'ano')},
            },
        ),
    ]
