# Generated by Django 5.1.7 on 2025-04-19 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_periodoformulario_alter_captacao_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('efetivou_operacao', models.BooleanField(verbose_name='Efetivou alguma operação/Indicação?')),
                ('descricao_operacao', models.TextField(blank=True, verbose_name='Se sim, com quais áreas?')),
                ('rv', models.BooleanField(verbose_name='RV')),
                ('cambio', models.BooleanField(verbose_name='Câmbio')),
                ('seguros', models.BooleanField(verbose_name='Seguros')),
                ('consorcio', models.BooleanField(verbose_name='Consórcio')),
                ('corporate', models.BooleanField(verbose_name='Corporate')),
                ('expansao', models.BooleanField(verbose_name='Expansão')),
                ('banking', models.BooleanField(verbose_name='Banking (Cartão/Folha de pagamento)')),
                ('advisory', models.BooleanField(verbose_name='Advisory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
