# Generated by Django 5.1.7 on 2025-04-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_estatisticas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatisticas',
            name='advisory',
            field=models.BooleanField(default=False, verbose_name='Advisory'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='banking',
            field=models.BooleanField(default=False, verbose_name='Banking'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='cambio',
            field=models.BooleanField(default=False, verbose_name='Câmbio'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='consorcio',
            field=models.BooleanField(default=False, verbose_name='Consórcio'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='corporate',
            field=models.BooleanField(default=False, verbose_name='Corporate'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='efetivou_operacao',
            field=models.BooleanField(default=False, verbose_name='Efetivou alguma operação/Indicação?'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='expansao',
            field=models.BooleanField(default=False, verbose_name='Expansão'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='rv',
            field=models.BooleanField(default=False, verbose_name='RV'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='seguros',
            field=models.BooleanField(default=False, verbose_name='Seguros'),
        ),
    ]
