# Generated by Django 5.1.7 on 2025-04-19 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_estatisticas_advisory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MASTER', 'Master'), ('HEAD', 'Head'), ('ASSESSOR', 'Assessor')], default='ASSESSOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cdi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
