# Generated by Django 5.1.7 on 2025-04-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser_head_customuser_role_alter_customuser_cdi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cdi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
