# Generated by Django 5.1.7 on 2025-04-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customuser_cdi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cdi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
