# Generated by Django 5.1.7 on 2025-04-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_customuser_cdi_alter_customuser_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='head',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
