# Generated by Django 5.1.7 on 2025-04-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_customuser_head_remove_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captacao',
            name='acao',
            field=models.CharField(choices=[('Marcar 1ª Reunião', 'Marcar 1ª Reunião'), ('Marcar 2ª Reunião', 'Marcar 2ª Reunião'), ('Abrir conta', 'Abrir conta'), ('Pedir TED', 'Pedir TED'), ('Trocar Assessoria', 'Trocar Assessoria'), ('Fazer STVM', 'Fazer STVM'), ('Não Selecionado', 'Não Selecionado')], default='Não Selecionado', max_length=50, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='captacao',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do cliente'),
        ),
        migrations.AlterField(
            model_name='captacao',
            name='origem',
            field=models.CharField(choices=[('Família', 'Família'), ('Relacionamento', 'Relacionamento'), ('Indicação', 'Indicação'), ('Redes Sociais', 'Redes Sociais'), ('Palestras', 'Palestras'), ('Alunos', 'Alunos'), ('Já é cliente', 'Já é cliente'), ('Não Selecionado', 'Não Selecionado')], default='Não Selecionado', max_length=50, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='captacao',
            name='pl',
            field=models.CharField(max_length=255, verbose_name='Produto Líquido'),
        ),
        migrations.AlterField(
            model_name='captacao',
            name='planejado_migracao',
            field=models.CharField(max_length=255, verbose_name='Planejado Migração'),
        ),
        migrations.AlterField(
            model_name='captacao',
            name='status',
            field=models.CharField(choices=[('Quente', 'Quente'), ('Morno', 'Morno'), ('Frio', 'Frio'), ('Não Selecionado', 'Não Selecionado')], default='Não Selecionado', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='executado',
            name='auc',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='executado',
            name='contratacoes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='executado',
            name='entrevistas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='executado',
            name='headcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='executado',
            name='nps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='executado',
            name='receita',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
