# Generated by Django 5.1.7 on 2025-04-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_captacao_acao_alter_captacao_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executado',
            name='contratacoes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='executado',
            name='entrevistas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='executado',
            name='headcount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='executado',
            name='nps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planejado',
            name='contratacoes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planejado',
            name='entrevistas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planejado',
            name='headcount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planejado',
            name='nps',
            field=models.IntegerField(null=True),
        ),
    ]
