# Generated by Django 5.1.7 on 2025-04-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_executado_contratacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executado',
            name='contratacoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executado',
            name='entrevistas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executado',
            name='headcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executado',
            name='nps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planejado',
            name='contratacoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planejado',
            name='entrevistas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planejado',
            name='headcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planejado',
            name='nps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
