# Generated by Django 5.1.7 on 2025-04-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_executado_contratacoes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodoFormulario',
        ),
    ]
