# Generated by Django 5.2 on 2025-04-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_unidade_alter_estatisticas_descricao_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='roa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
