# Generated by Django 5.2 on 2025-04-23 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_unidade_roa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.unidade'),
        ),
    ]
