# Generated by Django 5.1.7 on 2025-04-24 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
