# Generated by Django 5.1.7 on 2025-04-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_delete_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='area',
            field=models.CharField(blank=True, choices=[('comercial', 'Comercial'), ('investimentos', 'Investimentos'), ('operacoes', 'Operações'), ('', 'Nenhuma')], max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('master', 'Master'), ('head', 'Head'), ('assessor', 'Assessor')], default='assessor', max_length=20),
        ),
    ]
