# Generated by Django 5.1.7 on 2025-04-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_customuser_area_customuser_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area',
            field=models.CharField(blank=True, choices=[('comercial', 'Comercial'), ('investimentos', 'Investimentos'), ('operacoes', 'Operações'), ('', 'Nenhuma')], default='', max_length=30, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('master', 'Master'), ('head', 'Head de Área'), ('assessor', 'Assessor')], default='assessor', max_length=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cdi',
            field=models.CharField(blank=True, max_length=50, verbose_name='CDI'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone'),
        ),
    ]
