# Generated by Django 5.1.7 on 2025-04-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_customuser_area_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatisticas',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='Motivo de não ter feito operação'),
        ),
        migrations.AddField(
            model_name='estatisticas',
            name='qtd_advisory',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de operações Advisory'),
        ),
        migrations.AddField(
            model_name='estatisticas',
            name='qtd_banking',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de operações Banking'),
        ),
        migrations.AddField(
            model_name='estatisticas',
            name='qtd_cambio',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de operações Câmbio'),
        ),
        migrations.AddField(
            model_name='estatisticas',
            name='qtd_consorcio',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de operações Consórcio'),
        ),
        migrations.AddField(
            model_name='estatisticas',
            name='qtd_corporate',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de operações Corporate'),
        ),
        migrations.AddField(
            model_name='estatisticas',
            name='qtd_expansao',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de operações Expansão'),
        ),
        migrations.AddField(
            model_name='estatisticas',
            name='qtd_rv',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de operações RV'),
        ),
        migrations.AddField(
            model_name='estatisticas',
            name='qtd_seguros',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de operações Seguros'),
        ),
        migrations.AlterField(
            model_name='captacao',
            name='pl',
            field=models.CharField(max_length=255, verbose_name='Patrimônio Líquido do cliente'),
        ),
    ]
