# Generated by Django 5.1.7 on 2025-04-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_estatisticas_motivo_estatisticas_qtd_advisory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captacao',
            name='pl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Patrimônio Líquido do cliente'),
        ),
        migrations.AlterField(
            model_name='captacao',
            name='planejado_migracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Planejado Migração'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='advisory',
            field=models.BooleanField(default=None, verbose_name='Advisory'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='banking',
            field=models.BooleanField(default=None, verbose_name='Banking'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='cambio',
            field=models.BooleanField(default=None, verbose_name='Câmbio'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='consorcio',
            field=models.BooleanField(default=None, verbose_name='Consórcio'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='corporate',
            field=models.BooleanField(default=None, verbose_name='Corporate'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='efetivou_operacao',
            field=models.BooleanField(default=None, verbose_name='Efetivou alguma operação/Indicação?'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='expansao',
            field=models.BooleanField(default=None, verbose_name='Expansão'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='rv',
            field=models.BooleanField(default=None, verbose_name='RV'),
        ),
        migrations.AlterField(
            model_name='estatisticas',
            name='seguros',
            field=models.BooleanField(default=None, verbose_name='Seguros'),
        ),
    ]
