# Generated by Django 5.1.7 on 2025-04-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alertaduplicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captacao',
            name='pl',
            field=models.CharField(default=0, max_length=30, verbose_name='Patrimônio Líquido do cliente'),
        ),
    ]
