# Generated by Django 5.1.7 on 2025-04-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_captacao_pl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertaduplicado',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='alertaduplicado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='captacao',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='captacao',
            name='email',
        ),
    ]
