# Generated by Django 5.1.7 on 2025-05-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_alertaduplicado_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area',
            field=models.CharField(blank=True, choices=[('expansao', 'Expansão'), ('seguro', 'Seguros'), ('renda_variavel', 'Renda Variável'), ('cambio', 'Câmbio'), ('corporate', 'Corporate'), ('banking', 'Banking'), ('consorcio', 'Consórcio'), ('advisory', 'Advisory'), ('marketing', 'Marketing'), ('', 'Nenhuma')], default='', max_length=30, verbose_name='Área'),
        ),
    ]
