# Generated by Django 5.1.7 on 2025-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_customuser_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoEdicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Código de Edição',
                'verbose_name_plural': 'Código de Edição',
            },
        ),
    ]
