# Generated by Django 5.1.7 on 2025-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_codigoedicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cdi',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cge',
            field=models.CharField(blank=True, max_length=50, verbose_name='CGE'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('master', 'Master'), ('head', 'Head de Área'), ('assessor', 'Assessor'), ('headunidade', 'Head de Unidade')], default='assessor', max_length=20, verbose_name='Cargo'),
        ),
    ]
