# Generated by Django 5.1.7 on 2025-05-08 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_area_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_gerenciadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
