# Generated by Django 5.1.7 on 2025-05-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_customuser_contas_novas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contas_novas',
        ),
    ]
