# Generated by Django 5.1.7 on 2025-05-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_fix_estatisticas_qty_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='captacao',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentários (opcional)'),
        ),
        migrations.AddField(
            model_name='estatisticas',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentários (opcional)'),
        ),
    ]
