# Generated by Django 5.1.7 on 2025-05-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_captacao_comentario_estatisticas_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamentomensal',
            options={'verbose_name': 'Agendamento Mensal', 'verbose_name_plural': 'Agendamentos Mensais'},
        ),
        migrations.AddField(
            model_name='agendamentomensal',
            name='dias_especificos',
            field=models.CharField(blank=True, help_text='Dias específicos do mês separados por vírgula (ex: 1,5,10,15,20,25)', max_length=200),
        ),
        migrations.AddField(
            model_name='agendamentomensal',
            name='recorrente',
            field=models.BooleanField(default=True, help_text='Se marcado, este agendamento será automaticamente criado para o próximo mês'),
        ),
        migrations.AlterField(
            model_name='agendamentomensal',
            name='nome',
            field=models.CharField(choices=[('Planejado', 'Planejado'), ('Executado', 'Executado'), ('Estatísticas', 'Estatísticas')], max_length=20),
        ),
    ]
