# Generated by Django 5.1.7 on 2025-05-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_agendamentomensal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='area',
        ),
    ]
