# Generated by Django 5.1.7 on 2025-05-10 02:34

from django.db import migrations


def clear_assessor_area_refs(apps, schema_editor):
    # Get the historical model versions
    CustomUser = apps.get_model('main', 'CustomUser')
    
    # Get all assessors
    assessors = CustomUser.objects.filter(cargo='assessor')
    
    # Clear their area_ref field
    assessors.update(area_ref=None)
    
    print(f"Cleared area references for {assessors.count()} assessors.")


def reverse_migration(apps, schema_editor):
    # No need to restore the area references
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_customuser_area'),
    ]

    operations = [
        migrations.RunPython(clear_assessor_area_refs, reverse_migration),
    ]
