# Generated by Django 5.1.7 on 2025-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_executado_assessores_ativos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captacao',
            name='pl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Patrimônio Líquido do cliente'),
        ),
        migrations.AlterField(
            model_name='captacao',
            name='planejado_migracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Planejado Migração'),
        ),
    ]
