# Generated by Django 5.1.7 on 2025-05-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_captacao_pl_alter_captacao_planejado_migracao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executado',
            old_name='headcount',
            new_name='assessores_ativos',
        ),
        migrations.RenameField(
            model_name='planejado',
            old_name='headcount',
            new_name='assessores_ativos',
        ),
        migrations.AddField(
            model_name='executado',
            name='captacao_mesa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='cartoes_emitidos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='cpfs_operados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='interacoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='leads_sociais',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='ofertas_publicas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='pace',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='percentual_atingido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='percentual_pl_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='percentual_pl_liquidez',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='pl_liquidez',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='principalidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='qtd_consorcios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='qtd_reunioes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='qtd_seguros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='seguidores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='volume_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='volume_financeiro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='volume_ofertas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='volume_operado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='executado',
            name='volume_pa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='captacao_mesa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='cartoes_emitidos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='cpfs_operados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='interacoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='leads_sociais',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='ofertas_publicas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='pace',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='percentual_atingido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='percentual_pl_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='percentual_pl_liquidez',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='pl_liquidez',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='principalidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='qtd_consorcios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='qtd_reunioes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='qtd_seguros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='seguidores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='volume_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='volume_financeiro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='volume_ofertas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='volume_operado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='volume_pa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='executado',
            name='receita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='planejado',
            name='receita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
