# Generated by Django 5.1.7 on 2025-05-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_rename_headcount_executado_assessores_ativos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='planejado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
