# Generated by Django 5.1.7 on 2025-06-25 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_executado_updated_at_planejado_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('objetivo_auc', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Objetivo AUC Anual (R$)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_unidade_definidos', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_anuais', to='main.unidade')),
            ],
            options={
                'verbose_name': 'Objetivo de Unidade',
                'verbose_name_plural': 'Objetivos de Unidade',
                'unique_together': {('unidade', 'year')},
            },
        ),
    ]
