# Generated by Django 5.1.7 on 2025-07-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_objetivounidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('auc', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('receita_pj1', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('receita_pj2', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('receita_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
