# Generated by Django 5.1.7 on 2025-07-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_financehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financehistory',
            name='auc',
        ),
    ]
